package opencode

var ModelList = []string{
	"claude-fable-5",
	"claude-opus-5",
	"claude-opus-4-8",
	"claude-opus-4-7",
	"claude-opus-4-6",
	"claude-opus-4-5",
	"claude-sonnet-5",
	"claude-sonnet-4-6",
	"claude-sonnet-4-5",
	"claude-sonnet-4",
	"claude-haiku-4-5",
	"gemini-3.6-flash",
	"gemini-3.5-flash-lite",
	"gemini-3.5-flash",
	"gemini-3.1-pro",
	"gemini-3-flash",
	"gpt-5.6-sol",
	"gpt-5.6-terra",
	"gpt-5.6-luna",
	"gpt-5.5",
	"gpt-5.5-pro",
	"gpt-5.4",
	"gpt-5.4-pro",
	"gpt-5.4-mini",
	"gpt-5.4-nano",
	"gpt-5.3-codex-spark",
	"gpt-5.3-codex",
	"gpt-5.2",
	"gpt-5.2-codex",
	"gpt-5.1",
	"gpt-5.1-codex-max",
	"gpt-5.1-codex",
	"gpt-5.1-codex-mini",
	"gpt-5",
	"gpt-5-codex",
	"gpt-5-nano",
	"grok-build-0.1",
	"grok-4.5",
	"deepseek-v4-pro",
	"deepseek-v4-flash",
	"glm-5.2",
	"glm-5.1",
	"glm-5",
	"minimax-m3",
	"minimax-m2.7",
	"minimax-m2.5",
	"kimi-k3",
	"kimi-k2.7-code",
	"kimi-k2.6",
	"kimi-k2.5",
	"qwen3.6-plus",
	"qwen3.5-plus",
	"big-pickle",
	"deepseek-v4-flash-free",
	"mimo-v2.5-free",
	"ling-3.0-flash-free",
	"nemotron-3-ultra-free",
	"north-mini-code-free",
	"laguna-s-2.1-free",
	"longcat-2.0-free",
}

const ChannelName = "opencode-zen"

var GoModelList = []string{
	"minimax-m3",
	"minimax-m2.7",
	"minimax-m2.5",
	"kimi-k3",
	"kimi-k2.7-code",
	"kimi-k2.6",
	"kimi-k2.5",
	"glm-5.2",
	"glm-5.1",
	"glm-5",
	"deepseek-v4-pro",
	"deepseek-v4-flash",
	"qwen3.7-max",
	"qwen3.8-max",
	"qwen3.7-plus",
	"qwen3.6-plus",
	"qwen3.5-plus",
	"mimo-v2-pro",
	"mimo-v2-omni",
	"mimo-v2.5-pro",
	"mimo-v2.5",
	"hy3",
	"hy3-preview",
	"gpt-5.6-luna",
	"grok-4.5",
}

const GoChannelName = "opencode-go"
